Fix version local
outscale/cloud-provider-osc pull request #342
Opened 2024-01-25 10:27 UTC by outscale-vbr

Fix version local

2024-01-25 11:07 UTC, outscale-mdr commented
Could you remove unused lines in [.github/workflows/e2e_test.yml](https://github.com/outscale/cloud-provider-osc/blob/b620f4c8ab2950131269e27a4421703e36c52f31/.github/workflows/e2e_test.yml#L70) to avoid confusion ?

2024-01-25 12:43 UTC, outscale-vbr commented
Yes

2024-01-25 13:06 UTC, outscale-mdr requested changes

2024-01-25 13:06 UTC, outscale-mdr commented on .github/workflows/e2e_test.yml
>          control_plane_vm_type: ${{ secrets.CP_VMTYPE }}
This is not used, right ?

2024-01-25 14:27 UTC, outscale-vbr commented on .github/workflows/e2e_test.yml
>          control_plane_vm_type: ${{ secrets.CP_VMTYPE }}
Yes i remove too

2024-01-26 10:32 UTC, outscale-vbr commented
@outscale-mdr ARe you ok with the latest changes ?

2024-01-31 14:23 UTC, outscale-mdr approved these changes

2024-01-31 14:31 UTC, merged